# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/xcl_design_ddrmem_0.xci
# IP: The module: 'xcl_design_ddrmem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_0/xcl_design_ddrmem_0_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_0_microblaze_mcs || ORIG_REF_NAME==xcl_design_ddrmem_0_microblaze_mcs}]

# Block Designs: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/bd_3016.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016 || ORIG_REF_NAME==bd_3016}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_0/bd_3016_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_microblaze_I_0 || ORIG_REF_NAME==bd_3016_microblaze_I_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_1/bd_3016_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_rst_0_0 || ORIG_REF_NAME==bd_3016_rst_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_2/bd_3016_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_ilmb_0 || ORIG_REF_NAME==bd_3016_ilmb_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_3/bd_3016_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_dlmb_0 || ORIG_REF_NAME==bd_3016_dlmb_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_4/bd_3016_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_dlmb_cntlr_0 || ORIG_REF_NAME==bd_3016_dlmb_cntlr_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_5/bd_3016_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_ilmb_cntlr_0 || ORIG_REF_NAME==bd_3016_ilmb_cntlr_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_6/bd_3016_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_lmb_bram_I_0 || ORIG_REF_NAME==bd_3016_lmb_bram_I_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_7/bd_3016_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_3016_second_dlmb_cntlr_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_8/bd_3016_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_3016_second_ilmb_cntlr_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_9/bd_3016_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_3016_second_lmb_bram_I_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_10/bd_3016_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_iomodule_0_0 || ORIG_REF_NAME==bd_3016_iomodule_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_1/xcl_design_ddrmem_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_0_phy || ORIG_REF_NAME==xcl_design_ddrmem_0_phy}]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_0/bd_3016_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_microblaze_I_0 || ORIG_REF_NAME==bd_3016_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_0/bd_3016_microblaze_I_0_ooc_debug.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_0/bd_3016_microblaze_I_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_1/bd_3016_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_rst_0_0 || ORIG_REF_NAME==bd_3016_rst_0_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_1/bd_3016_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_rst_0_0 || ORIG_REF_NAME==bd_3016_rst_0_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_1/bd_3016_rst_0_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_2/bd_3016_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_ilmb_0 || ORIG_REF_NAME==bd_3016_ilmb_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_2/bd_3016_ilmb_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_3/bd_3016_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_dlmb_0 || ORIG_REF_NAME==bd_3016_dlmb_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_3/bd_3016_dlmb_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_4/bd_3016_dlmb_cntlr_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_5/bd_3016_ilmb_cntlr_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_6/bd_3016_lmb_bram_I_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_7/bd_3016_second_dlmb_cntlr_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_8/bd_3016_second_ilmb_cntlr_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_9/bd_3016_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_10/bd_3016_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_iomodule_0_0 || ORIG_REF_NAME==bd_3016_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_10/bd_3016_iomodule_0_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/bd_3016_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_0/xcl_design_ddrmem_0_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_0_microblaze_mcs || ORIG_REF_NAME==xcl_design_ddrmem_0_microblaze_mcs}] {/inst }]/inst ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_0/xcl_design_ddrmem_0_microblaze_mcs_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_1/par/xcl_design_ddrmem_0_phy_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/xcl_design_ddrmem_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_ddrmem_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/par/xcl_design_ddrmem_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_ddrmem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/xcl_design_ddrmem_0.xci
# IP: The module: 'xcl_design_ddrmem_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_0/xcl_design_ddrmem_0_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_0_microblaze_mcs || ORIG_REF_NAME==xcl_design_ddrmem_0_microblaze_mcs}]

# Block Designs: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/bd_3016.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016 || ORIG_REF_NAME==bd_3016}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_0/bd_3016_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_microblaze_I_0 || ORIG_REF_NAME==bd_3016_microblaze_I_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_1/bd_3016_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_rst_0_0 || ORIG_REF_NAME==bd_3016_rst_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_2/bd_3016_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_ilmb_0 || ORIG_REF_NAME==bd_3016_ilmb_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_3/bd_3016_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_dlmb_0 || ORIG_REF_NAME==bd_3016_dlmb_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_4/bd_3016_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_dlmb_cntlr_0 || ORIG_REF_NAME==bd_3016_dlmb_cntlr_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_5/bd_3016_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_ilmb_cntlr_0 || ORIG_REF_NAME==bd_3016_ilmb_cntlr_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_6/bd_3016_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_lmb_bram_I_0 || ORIG_REF_NAME==bd_3016_lmb_bram_I_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_7/bd_3016_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_3016_second_dlmb_cntlr_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_8/bd_3016_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_3016_second_ilmb_cntlr_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_9/bd_3016_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_3016_second_lmb_bram_I_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_10/bd_3016_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_3016_iomodule_0_0 || ORIG_REF_NAME==bd_3016_iomodule_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_1/xcl_design_ddrmem_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_0_phy || ORIG_REF_NAME==xcl_design_ddrmem_0_phy}]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_0/bd_3016_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_microblaze_I_0 || ORIG_REF_NAME==bd_3016_microblaze_I_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_0/bd_3016_microblaze_I_0_ooc_debug.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_0/bd_3016_microblaze_I_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_1/bd_3016_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_rst_0_0 || ORIG_REF_NAME==bd_3016_rst_0_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_1/bd_3016_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_rst_0_0 || ORIG_REF_NAME==bd_3016_rst_0_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_1/bd_3016_rst_0_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_2/bd_3016_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_ilmb_0 || ORIG_REF_NAME==bd_3016_ilmb_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_2/bd_3016_ilmb_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_3/bd_3016_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_dlmb_0 || ORIG_REF_NAME==bd_3016_dlmb_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_3/bd_3016_dlmb_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_4/bd_3016_dlmb_cntlr_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_5/bd_3016_ilmb_cntlr_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_6/bd_3016_lmb_bram_I_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_7/bd_3016_second_dlmb_cntlr_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_8/bd_3016_second_ilmb_cntlr_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_9/bd_3016_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_10/bd_3016_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3016_iomodule_0_0 || ORIG_REF_NAME==bd_3016_iomodule_0_0}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/ip/ip_10/bd_3016_iomodule_0_0_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/bd_0/bd_3016_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_0/xcl_design_ddrmem_0_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==xcl_design_ddrmem_0_microblaze_mcs || ORIG_REF_NAME==xcl_design_ddrmem_0_microblaze_mcs}] {/inst }]/inst ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_0/xcl_design_ddrmem_0_microblaze_mcs_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/ip_1/par/xcl_design_ddrmem_0_phy_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/xcl_design_ddrmem_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_ddrmem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_ddrmem_0/par/xcl_design_ddrmem_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_ddrmem_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
