#!/bin/bash

set -e

export DIR
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck source=/dev/null
source "${CONFIG_FILE:-$HOME/.jarvice}"

function help {
    echo "

reco-jarvice $VERSION

usage: $0 <command>

Where <command> is one of the following:

    Testing:

    test <cmd>              Test the current kernel using a hardware simulator

    Building:

    build                   Build the project in the current folder.
    builds                  List previous builds

    Running builds:

    run <build id> <cmd>    Deploy an accelerated batch job to run on Nimbix

    Other:

    help    Display this help output
"
}

function shell {
    NUMBER=$(run-script "$DIR/examples/sshd.sh")
    ssh "$NUMBER"
    shutdown "$NUMBER"
}

function stop {
    jarvice_cli -username "$USERNAME" -apikey "$API_KEY" shutdown_all
}

function shutdown {
    jarvice_cli -username "$USERNAME" -apikey "$API_KEY" shutdown -number "$1"
}

function builds {
    JOBS=$(curl "https://api.jarvice.com/jarvice/jobs?username=$USERNAME&apikey=$API_KEY&completed=true")

    echo -e "id\t\t\t\t\tstarted\t\t\tstatus"
    echo "$JOBS" | jq -r ".[] | values | select(.job_api_submission.application.parameters.command | select(. != null) | test(\"^/data/reco/$VERSION/workflows/build.sh\") ) | [(.job_label | split(\":\") | .[1]), (.job_start_time | todateiso8601), .job_status] | @tsv" | sort -r -k2
}

function ssh {
    NUMBER="$1"
    ERROR=dummy
    while [ "$ERROR" != "null" ]
    do
        CONNECTION_INFO=$(jarvice_cli -username "$USERNAME" -apikey "$API_KEY" connect -number "$NUMBER")
        ERROR=$(echo "$CONNECTION_INFO" | jq -r ".error")
    done

    ADDRESS=$(echo "$CONNECTION_INFO" | jq -r ".address")
    PASS=$(echo "$CONNECTION_INFO" | jq -r ".password")

    ansible localhost -m wait_for -a "host=$ADDRESS port=22 delay=0 timeout=300 state=started" > /dev/null

    sshpass -p "$PASS" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "nimbix@$ADDRESS" || true
}

function build {
    JOB=$(uuidgen -t)

    lftp "sftp://$USERNAME:$API_KEY@drop.jarvice.com" -e "set sftp:auto-confirm yes; mirror --reverse --exclude .reco-work -P4 $PWD/ job/$JOB; quit" 1>&2

    JSON=$(jq ".application.parameters.command = \"/data/reco/$VERSION/workflows/build.sh $JOB $*\" | .job_label = \"build:$JOB\" | .user.username = \"$USERNAME\" | .user.apikey = \"$API_KEY\"" < "$DIR/batch.json")
    JOB_DATA=$(jarvice_cli -username "$USERNAME" -apikey "$API_KEY" submit -j "$JSON")
    NUMBER=$(echo "$JOB_DATA" | jq -r ".number")
    wait_for "$NUMBER"
    echo "$JOB"
}

function test-cmd {
    JOB=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1)

    lftp "sftp://$USERNAME:$API_KEY@drop.jarvice.com" -e "set sftp:auto-confirm yes; mkdir tmp/tests/$JOB; mirror --reverse --exclude .reco-work -P4 $PWD/ tmp/tests/$JOB; quit" 1>&2

    JSON=$(jq ".application.parameters.command = \"/data/reco/$VERSION/workflows/simulate.sh $JOB $*\" | .job_label = \"simulate:$JOB\" | .user.username = \"$USERNAME\" | .user.apikey = \"$API_KEY\"" < "$DIR/batch.json")
    JOB_DATA=$(jarvice_cli -username "$USERNAME" -apikey "$API_KEY" submit -j "$JSON")
    NUMBER=$(echo "$JOB_DATA" | jq -r ".number")
    wait_for "$NUMBER"
    lftp "sftp://$USERNAME:$API_KEY@drop.jarvice.com" -e "set sftp:auto-confirm yes; rm -rf tmp/tests/$JOB; quit" > /dev/null
}

function run-script {
    JOB=$(uuidgen -t)
    FILENAME=$(basename "$1")

    lftp "sftp://$USERNAME:$API_KEY@drop.jarvice.com" -e "set sftp:auto-confirm yes; mirror --reverse -f $1 -O job/$JOB/; quit" 1>&2

    JSON=$(jq ".application.parameters.command = \"/data/job/$JOB/$FILENAME\" | .job_label = \"$JOB\"  | .user.username = \"$USERNAME\" | .user.apikey = \"$API_KEY\"" < "$DIR/batch.json")

    JOB=$(jarvice_cli -username "$USERNAME" -apikey "$API_KEY" submit -j "$JSON")
    NUMBER=$(echo "$JOB" | jq -r ".number")
    echo "$NUMBER"
}

function workflow {
    WORKFLOW="$1"
    JSON=$(jq ".application.parameters.command = \"/data/reco/$VERSION/workflows/$WORKFLOW\" | .user.username = \"$USERNAME\" | .user.apikey = \"$API_KEY\"" < "$DIR/batch.json")

    JOB=$(jarvice_cli -username "$USERNAME" -apikey "$API_KEY" submit -j "$JSON")
    NUMBER=$(echo "$JOB" | jq -r ".number")
    echo "$NUMBER"
}

function run {
    JSON=$(jq ".application.parameters.executable = \"/job/$1/.reco-work/sdaccel/dist/$2\"  | .user.username = \"$USERNAME\" | .user.apikey = \"$API_KEY\"" < "$DIR/deploy.json")

    JOB=$(jarvice_cli -username "$USERNAME" -apikey "$API_KEY" submit -j "$JSON")
    NUMBER=$(echo "$JOB" | jq -r ".number")
    wait_for "$NUMBER"
}

function wait_for {
    NUMBER="$1"
    jarvice_cli -username "$USERNAME" -apikey "$API_KEY" wait_for -number "$NUMBER" > /dev/null
    STATUS=$(jarvice_cli -username "$USERNAME" -apikey "$API_KEY" status -number "$NUMBER" | jq -r ".[\"$NUMBER\"].job_status")
    jarvice_cli -username "$USERNAME" -apikey "$API_KEY" output -number "$NUMBER" -lines 0 1>&2
    if [ "$STATUS" == "COMPLETED WITH ERROR" ]
    then
        exit 1;
    fi
}

function version {
    echo "$VERSION"
}


function main {
    case "$1" in
        "test")
            test-cmd "${@:2}"
            ;;
        "build")
            build "${@:2}"
            ;;
        "builds")
            builds "${@:2}"
            ;;
        "shell")
            shell "${@:2}"
            ;;
        "run-script")
            run-script "${@:2}"
            ;;
        "ssh")
            ssh "${@:2}"
            ;;
        "workflow")
            workflow "${@:2}"
            ;;
        "wait")
            wait_for "${@:2}"
            ;;
        "shutdown")
            shutdown "${@:2}"
            ;;
        "run")
            run "${@:2}"
            ;;
        "stop")
            stop "${@:2}"
            ;;
        "help")
            help "$@"
            ;;
        "version")
            version "$@"
            ;;

        *)
            echo "unrecognized command: $1";
            help "$@"
            exit 1
            ;;
        esac
}

main "$@"
