#!/bin/bash

set -e
set -o pipefail

export DIR
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export ROOT_DIR="$PWD"

function build {
    FULL_PATH=$(readlink -f "$1")

    make -f "$DIR/reco-sdaccel.mk" TARGET=hw_emu INPUT_FILE="$FULL_PATH" kernel
}

function test_go {
    FULL_PATH=$(readlink -f "$1")

    make -f "$DIR/reco-sdaccel.mk" INPUT_FILE="$FULL_PATH" verilog
}

function simulate {
    echo "simulate"

}

function clean {
    make -f "$DIR/reco-sdaccel.mk" clean
}

function main {
    case "$1" in
        "build")
            build "${@:2}"
            ;;
        "simulate")
            simulate "${@:2}"
            ;;
        "test-go")
            test_go "${@:2}"
            ;;
        "clean")
            clean "${@:2}"
            ;;
        *)
            echo "unrecognized command: $1";
            exit 1
            ;;
        esac
}

main "$@"
