#!/bin/bash

set -e
set -o pipefail

export DIR
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export ROOT_DIR="$PWD"

function build {
    make -f "$DIR/sdaccel-builder.mk" TARGET=hw_emu kernel
}

function image {
    make -f "$DIR/sdaccel-builder.mk" TARGET=hw kernel
}

function test_go {
    make -f "$DIR/sdaccel-builder.mk" verilog
}

function simulate {
    CMD="$1"
    make -f "$DIR/sdaccel-builder.mk" TARGET=hw_emu sim cmds kernel
    export PATH="$PWD/.reco-work/sdaccel/dist/":$PATH

    # shellcheck source=/dev/null
    source "$XILINX_SDACCEL"/settings64.sh
    XCL_EMULATION_MODE=hw_emu XCL_BINDIR="$PWD/.reco-work/sdaccel/dist/xclbin" "$CMD" "${@:2}"
}

function cmds {
    make -f "$DIR/sdaccel-builder.mk" cmds
}

function clean {
    make -f "$DIR/sdaccel-builder.mk" clean
}

function main {
    case "$1" in
        "build")
            build "${@:2}"
            ;;
        "simulate")
            simulate "${@:2}"
            ;;
        "image")
            image "${@:2}"
            ;;
        "cmds")
            cmds "${@:2}"
            ;;
        "test-go")
            test_go "${@:2}"
            ;;
        "clean")
            clean "${@:2}"
            ;;
        *)
            echo "unrecognized command: $1";
            exit 1
            ;;
        esac
}

main "$@"
