#!/bin/bash

set -e
set -o pipefail

export DIR
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export ROOT_DIR="$PWD"
reco_optimize="yes"
reco_memory_interface="axi"
reco_memory_width=64
reco_ports=2

function parse_yaml {
    local prefix="$2"
    local s='[[:space:]]*'
    local w='[a-zA-Z0-9_]*'
    local fs
    fs=$(echo @|tr @ '\034')
    set +e
    # shellcheck disable=SC1117
    sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  "$1" |
        awk -F"$fs" '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'"$prefix"'",vn, $2, $3);
      }
   }'
   set -e
}

if [ -e 'reco.yml' ]; then
   eval "$(parse_yaml 'reco.yml' 'reco_')"
fi

export PATH="$DIR/smi/bin:$DIR/bin:$PATH"

# Merge timing and utilization reports.
# Exposed as the command report for easier testing without the full xocc flow.
# e.g. sdaccel-builder report
# Primarily will be used by the build & simulate commands
function report {
    make -e -f "$DIR/sdaccel-builder.mk" TARGET=hw_emu OPTIMIZE="$reco_optimize" MEMORY_INTERFACE="$reco_memory_interface" AXI_DATA_WIDTH="$reco_memory_width" PORTS="$reco_ports" report

}

function graph {
    make -e -f "$DIR/sdaccel-builder.mk" TARGET=hw OPTIMIZE="$reco_optimize" MEMORY_INTERFACE="$reco_memory_interface" AXI_DATA_WIDTH="$reco_memory_width" PORTS="$reco_ports" graph
}

function build {
    make -e -f "$DIR/sdaccel-builder.mk" TARGET=hw_emu OPTIMIZE="$reco_optimize" MEMORY_INTERFACE="$reco_memory_interface" AXI_DATA_WIDTH="$reco_memory_width" PORTS="$reco_ports" kernel sim
    # run reports after everything
    report
}

function image {
    make -e -f "$DIR/sdaccel-builder.mk" TARGET=hw OPTIMIZE="$reco_optimize" MEMORY_INTERFACE="$reco_memory_interface" AXI_DATA_WIDTH="$reco_memory_width" PORTS="$reco_ports" kernel
}

function test_go {
    make -e -f "$DIR/sdaccel-builder.mk" OPTIMIZE="$reco_optimize" MEMORY_INTERFACE="$reco_memory_interface" AXI_DATA_WIDTH="$reco_memory_width" PORTS="$reco_ports" verilog
}

function simulate {
    make -e -f "$DIR/sdaccel-builder.mk" TARGET=hw_emu OPTIMIZE="$reco_optimize" MEMORY_INTERFACE="$reco_memory_interface" AXI_DATA_WIDTH="$reco_memory_width" PORTS="$reco_ports" sim cmds kernel
    # run reports after everything
    report
    export PATH="$PWD/.reco-work/sdaccel/dist/":$PATH
    # This is for the emconfig.json
    cd "$PWD/.reco-work/sdaccel/dist/"

    # shellcheck source=/dev/null
    source "$XILINX_SDACCEL"/settings64.sh
    XCL_EMULATION_MODE=hw_emu XCL_BINDIR="$PWD/.reco-work/sdaccel/dist/xclbin" bash -c "$@"
}

function cmds {
    make -e -f "$DIR/sdaccel-builder.mk" cmds
}

function clean {
    make -e -f "$DIR/sdaccel-builder.mk" clean
}

function lint {
    test_go
    EXTRA=()
    if [ "$reco_memory_interface" == "smi" ]
    then
        EXTRA=("-DAXI_MASTER_DATA_WIDTH=$reco_memory_width" "-DAXI_MASTER_HAS_WID=1")
    fi

    verilator -Wall --lint-only -I".reco-work/sdaccel/verilog/includes" -I".reco-work/sdaccel/verilog/library" .reco-work/sdaccel/verilog/main.v "${EXTRA[@]}" --top-module sda_kernel_wrapper_gmem --report-unoptflat -Wno-UNUSED -Wno-UNDRIVEN -Wno-REDEFMACRO -Wno-DECLFILENAME
}

function main {
    case "$1" in
        "build")
            build "${@:2}"
            ;;
        "report")
            report "${@:2}"
            ;;
        "simulate")
            simulate "${@:2}"
            ;;
        "image")
            image "${@:2}"
            ;;
        "graph")
            graph "${@:2}"
            ;;
        "cmds")
            cmds "${@:2}"
            ;;
        "test-go")
            test_go "${@:2}"
            ;;
        "clean")
            clean "${@:2}"
            ;;
        "lint")
            lint "${@:2}"
            ;;
        *)
            echo "unrecognized command: $1";
            exit 1
            ;;
        esac
}

main "$@"
