- hosts: localhost
  gather_facts: False

  vars:
    version: 2016.3
    dev_build_hostname: dev-build.reconfigureio-infra.com

  tasks:
    - name: find our ami
      ec2_ami_find:
        owner: self
        ami_tags:
          service: vivado-ecs
          version: '{{ version }}'
          build: latest
          production: "yes"
        sort: creationDate
        sort_order: descending
        no_result_action: fail
      register: ami_find

    - name: Provision dev instance
      ec2:
         key_name: "{{ lookup('env', 'AWS_KEYPAIR') }}"
         instance_type: "t2.2xlarge"
         image: "{{ ami_find.results[0].ami_id }}"
         wait: true
         exact_count: 1
         region: "{{ lookup('env', 'AWS_REGION') }}"
         groups: ['default']
         count_tag:
            service: dev-build
         instance_tags:
            service: dev-build
         volumes:
           - device_name: /dev/sda1
             volume_size: 100
             delete_on_termination: true
             device_type: gp2
         instance_profile_name: ecsInstanceRole
      register: ec2

    - name: Create DNS Record
      route53:
        command: create
        zone: reconfigureio-infra.com
        record: "{{ item }}"
        type: A
        value: "{{ ec2.instances[0].public_ip }}"
        overwrite: yes
      when: ec2.changed and ec2.instances[0].state != "terminated"
      with_items:
        - '{{ dev_build_hostname }}'
        
    - name: Wait for SSH to come up
      wait_for: host="{{ item.public_dns_name }}" port=22 delay=60 timeout=320 state=started
      when: ec2.changed and item.state != "terminated"
      with_items: '{{ec2.instances}}'

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=tag_service_dev-build
      with_items: '{{ec2.instances}}'

    - name: Add new instance to launched
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: '{{ec2.instances}}'
