- hosts: localhost
  gather_facts: False

  vars:
    version: 2017.4
    dev_build_hostname: dev-build.reconfigureio-infra.com

  tasks:
    - name: find our ami
      ec2_ami_find:
        owner: self
        ami_tags:
          service: vivado-ecs
          version: '{{ version }}'
          build: latest
          staging: "yes"
        sort: creationDate
        sort_order: descending
        no_result_action: fail
      register: ami_find

    - name: Provision dev instance
      ec2:
         key_name: "{{ lookup('env', 'AWS_KEYPAIR') }}"
         instance_type: "t2.2xlarge"
         image: "{{ ami_find.results[0].ami_id }}"
         wait: true
         exact_count: 1
         region: "{{ lookup('env', 'AWS_REGION') }}"
         groups: ['default']
         count_tag:
            key_name: "{{ lookup('env', 'AWS_KEYPAIR') }}"
         instance_tags:
            service: dev-build
            key_name: "{{ lookup('env', 'AWS_KEYPAIR') }}"
         volumes:
           - device_name: /dev/sda1
             volume_size: 200
             delete_on_termination: true
             device_type: gp2
         instance_profile_name: batch-builder
      register: ec2

    - name: Wait for SSH to come up
      wait_for: host="{{ item.public_dns_name }}" port=22 delay=60 timeout=320 state=started
      when: ec2.changed and item.state != "terminated"
      with_items: '{{ec2.instances}}'

    - name: print address
      debug:
        msg: "Instance address is {{ ec2.instances[0].public_dns_name }}"
