#!/bin/bash

set -e

export DIR
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function help {
    echo "
usage: $0 <command>

Where <command> is one of the following:

    shell   Spin up a temporary development shell in the Nimbix cloud
    run <path to script>  Spin up a single shot run of a script in the data partition.
    deploy <job number> <exectutable> Deploy an accelerated batch job to run on Nimbix
    stop    Stop all running jobs

    help    Display this help output
"
}

function stop {
    jarvice_cli shutdown_all
}

function shell {
    JOB=$(jarvice_cli submit -j "$DIR/job-json.json")
    NUMBER=$(echo "$JOB" | jq -r ".number")

    ERROR=dummy
    while [ "$ERROR" != "null" ]
    do
        CONNECTION_INFO=$(jarvice_cli connect -number "$NUMBER")
        ERROR=$(echo "$CONNECTION_INFO" | jq -r ".error")
    done

    ADDRESS=$(echo "$CONNECTION_INFO" | jq -r ".address")
    PASS=$(echo "$CONNECTION_INFO" | jq -r ".password")

    ansible localhost -m wait_for -a "host=$ADDRESS port=22 delay=0 timeout=300 state=started"

    sshpass -p "$PASS" ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "nimbix@$ADDRESS" || true
    jarvice_cli shutdown -number "$NUMBER"
}

function run {
    source ~/.jarvice
    JOB=$(uuidgen -t)
    FILENAME=$(basename "$1")

    lftp "sftp://$USERNAME:$API_KEY@drop.jarvice.com" -e "mirror --reverse -f $1 -O job/$JOB/; quit"

    JSON=$(jq ".application.parameters.executable = \"/job/$JOB/$FILENAME\"" < "$DIR/deploy.json")

    JOB=$(jarvice_cli submit -j "$JSON")
    NUMBER=$(echo "$JOB" | jq -r ".number")
    jarvice_cli status -number "$NUMBER"
    jarvice_cli tail -number "$NUMBER"
}

function deploy {
    JSON=$(jq ".application.parameters.executable = \"/job/$1/$2\"" < "$DIR/deploy.json")

    JOB=$(jarvice_cli submit -j "$JSON")
    NUMBER=$(echo "$JOB" | jq -r ".number")
    jarvice_cli status -number "$NUMBER"
    jarvice_cli tail -number "$NUMBER"
}

function main {
    case "$1" in
        "shell")
            shell "${@:2}"
            ;;
        "run")
            run "${@:2}"
            ;;
        "deploy")
            deploy "${@:2}"
            ;;
        "stop")
            stop "${@:2}"
            ;;
        "help")
            help "$@"
            ;;

        *)
            echo "unrecognized command: $1";
            help "$@"
            exit 1
            ;;
        esac
}

main "$@"
