# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0.xci
# IP: The module: 'xcl_design_psreset_ddrmem_n_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_ddrmem_n_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_ddrmem_n_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_ddrmem_n_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0.xci
# IP: The module: 'xcl_design_psreset_ddrmem_n_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_ddrmem_n_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_ddrmem_n_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_psreset_ddrmem_n_2_0/xcl_design_psreset_ddrmem_n_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_psreset_ddrmem_n_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
