# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/xcl_design_flash_programmer_0.xci
# IP: The module: 'xcl_design_flash_programmer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/bitstream_fifo/bitstream_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitstream_fifo || ORIG_REF_NAME==bitstream_fifo}]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/bitstream_fifo/bitstream_fifo/bitstream_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bitstream_fifo || ORIG_REF_NAME==bitstream_fifo}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/bitstream_fifo/bitstream_fifo/bitstream_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bitstream_fifo || ORIG_REF_NAME==bitstream_fifo}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/bitstream_fifo/bitstream_fifo_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/flash_programmer.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_flash_programmer_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/xcl_design_flash_programmer_0.xci
# IP: The module: 'xcl_design_flash_programmer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/bitstream_fifo/bitstream_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bitstream_fifo || ORIG_REF_NAME==bitstream_fifo}]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/bitstream_fifo/bitstream_fifo/bitstream_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bitstream_fifo || ORIG_REF_NAME==bitstream_fifo}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/bitstream_fifo/bitstream_fifo/bitstream_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bitstream_fifo || ORIG_REF_NAME==bitstream_fifo}] {/U0 }]/U0 ]]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/bitstream_fifo/bitstream_fifo_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_flash_programmer_0/src/flash_programmer.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_flash_programmer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
