# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0.xci
# IP: The module: 'xcl_design_u_ocl_region_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/bd_2fd7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7 || ORIG_REF_NAME==bd_2fd7}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_0/bd_2fd7_m_axi_interconnect_M00_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M00_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M00_AXI_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_2/bd_2fd7_m_axi_interconnect_M01_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M01_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M01_AXI_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_4/bd_2fd7_s_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s_axi_interconnect_0_0 || ORIG_REF_NAME==bd_2fd7_s_axi_interconnect_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_5/bd_2fd7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_xbar_0 || ORIG_REF_NAME==bd_2fd7_xbar_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_8/bd_2fd7_interconnect_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_interconnect_sys_reset_0 || ORIG_REF_NAME==bd_2fd7_interconnect_sys_reset_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_9/bd_2fd7_kernel_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_sys_reset_0 || ORIG_REF_NAME==bd_2fd7_kernel_sys_reset_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_10/bd_2fd7_kernel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_0_0 || ORIG_REF_NAME==bd_2fd7_kernel_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_11/bd_2fd7_kernel_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_1_0 || ORIG_REF_NAME==bd_2fd7_kernel_1_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_12/bd_2fd7_slave_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_slave_bridge_0 || ORIG_REF_NAME==bd_2fd7_slave_bridge_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_13/bd_2fd7_master_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_0_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_14/bd_2fd7_master_bridge_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_1_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_1_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_1/bd_2fd7_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_0 || ORIG_REF_NAME==bd_2fd7_s00_regslice_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_3/bd_2fd7_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_1 || ORIG_REF_NAME==bd_2fd7_s00_regslice_1}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_6/bd_2fd7_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m00_regslice_0 || ORIG_REF_NAME==bd_2fd7_m00_regslice_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_7/bd_2fd7_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m01_regslice_0 || ORIG_REF_NAME==bd_2fd7_m01_regslice_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_15/bd_2fd7_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_0 || ORIG_REF_NAME==bd_2fd7_auto_cc_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_16/bd_2fd7_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_1 || ORIG_REF_NAME==bd_2fd7_auto_cc_1}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_17/bd_2fd7_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_2 || ORIG_REF_NAME==bd_2fd7_auto_cc_2}]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/bd_2fd7_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_u_ocl_region_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0.xci
# IP: The module: 'xcl_design_u_ocl_region_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/bd_2fd7.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7 || ORIG_REF_NAME==bd_2fd7}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_0/bd_2fd7_m_axi_interconnect_M00_AXI_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M00_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M00_AXI_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_2/bd_2fd7_m_axi_interconnect_M01_AXI_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m_axi_interconnect_M01_AXI_0 || ORIG_REF_NAME==bd_2fd7_m_axi_interconnect_M01_AXI_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_4/bd_2fd7_s_axi_interconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s_axi_interconnect_0_0 || ORIG_REF_NAME==bd_2fd7_s_axi_interconnect_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_5/bd_2fd7_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_xbar_0 || ORIG_REF_NAME==bd_2fd7_xbar_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_8/bd_2fd7_interconnect_sys_reset_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_interconnect_sys_reset_0 || ORIG_REF_NAME==bd_2fd7_interconnect_sys_reset_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_9/bd_2fd7_kernel_sys_reset_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_sys_reset_0 || ORIG_REF_NAME==bd_2fd7_kernel_sys_reset_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_10/bd_2fd7_kernel_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_0_0 || ORIG_REF_NAME==bd_2fd7_kernel_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_11/bd_2fd7_kernel_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_kernel_1_0 || ORIG_REF_NAME==bd_2fd7_kernel_1_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_12/bd_2fd7_slave_bridge_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_slave_bridge_0 || ORIG_REF_NAME==bd_2fd7_slave_bridge_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_13/bd_2fd7_master_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_0_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_0_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_14/bd_2fd7_master_bridge_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_master_bridge_1_0 || ORIG_REF_NAME==bd_2fd7_master_bridge_1_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_1/bd_2fd7_s00_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_0 || ORIG_REF_NAME==bd_2fd7_s00_regslice_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_3/bd_2fd7_s00_regslice_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_s00_regslice_1 || ORIG_REF_NAME==bd_2fd7_s00_regslice_1}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_6/bd_2fd7_m00_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m00_regslice_0 || ORIG_REF_NAME==bd_2fd7_m00_regslice_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_7/bd_2fd7_m01_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_m01_regslice_0 || ORIG_REF_NAME==bd_2fd7_m01_regslice_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_15/bd_2fd7_auto_cc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_0 || ORIG_REF_NAME==bd_2fd7_auto_cc_0}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_16/bd_2fd7_auto_cc_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_1 || ORIG_REF_NAME==bd_2fd7_auto_cc_1}]

# IP: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/ip/ip_17/bd_2fd7_auto_cc_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_2fd7_auto_cc_2 || ORIG_REF_NAME==bd_2fd7_auto_cc_2}]

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/bd_0/bd_2fd7_ooc.xdc

# XDC: /home/joshbohde/code/nerabus/refdesign_test/adm-pcie-ku3_2ddr_3.1/adm-pcie-ku3_2ddr_3.1.srcs/sources_1/bd/xcl_design/ip/xcl_design_u_ocl_region_0/xcl_design_u_ocl_region_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xcl_design_u_ocl_region_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
